### PR TITLE
Fix reporting authorization

### LINKED ISSUE #535: Organization report breaks usage isolation
Resource providers can see other resource providers date through the organization report.

We can limit the org report access and require system token access.
The resource instance report should be accessible only to the respective resource providers that have token with `.write` scope.

### PR DESCRIPTION
**Pull request by nmaslarski**
Fixes #535
[delivers #139495947]

### CODE REVIEW

File: test/perf/src/test/test.js [hunk 1]
```diff
@@ -293,16 +293,43 @@ describe('abacus-perf-test', () => {
       ]
     };
 
+    const token2 = {
```
Comment (hsiliev) [inline test/perf/src/test/test.js]: Can we rename the token to "systemReadToken" and the one above to something like "objectStorageWriteToken" (or shorter) to make the purpose of the tokens more obvious ?

File: test/perf/src/test/test.js [hunk 2]
```diff
@@ -293,16 +293,43 @@ describe('abacus-perf-test', () => {
...
+    };
+
     // OAuth bearer access token signed using JWTKEY and
     // default algorithm (HS256)
     const auth = process.env.SECURED === 'true' ?
       jwt.sign(token, process.env.JWTKEY, {
         algorithm: process.env.JWTALGO,
         expiresIn: 43200
       }) : undefined;
+    const auth2 = process.env.SECURED === 'true' ?
```
Comment (hsiliev) [inline test/perf/src/test/test.js]: Same here - we need better names for the variables.
